name: presence_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  firebase_core: ^3.15.2
  shared_preferences: ^2.2.2
  cloud_functions: ^5.6.2
  rxdart: ^0.27.7
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  qr_flutter: ^4.1.0
  uuid: ^4.5.1
  intl: ^0.20.2
  mobile_scanner: ^4.0.0
  permission_handler: ^11.0.1
  image_picker: ^1.0.4
  firebase_storage: ^12.4.10
  cached_network_image: ^3.3.0
  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8
  animate_do: ^4.2.0
  geolocator: ^11.0.1
  geocoding: ^2.2.0
  camera: ^0.10.6
  printing: ^5.10.2
  pdf: ^3.10.2

  image: ^4.0.17
  path_provider: ^2.1.1



# DÉPLACEZ CES PACKAGES DANS dev_dependencies :
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.7

# CONFIGURATIONS AU NIVEAU RACINE :
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher_icon.png"
  adaptive_icon_background: "#6366F1"
  adaptive_icon_foreground: "assets/images/launcher_icon.png"

flutter_native_splash:
  color: "#6366F1"
  image: "assets/images/splash.png"
  android: true
  ios: true
  web: true
  branding: "assets/images/launcher_icon.png"

flutter_intl:
  enabled: true

# SECTION FLUTTER :
flutter:
  uses-material-design: true

  assets:
    - assets/register.jpg
    - assets/
    - assets/images/