// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNf8uQ6LbE1D-lz8bq8ccGP1JsjB6_4fU',
    appId: '1:889075244343:web:2478fda6c964e5b857ceb2',
    messagingSenderId: '889075244343',
    projectId: 'presence-app-26d2d',
    authDomain: 'presence-app-26d2d.firebaseapp.com',
    storageBucket: 'presence-app-26d2d.firebasestorage.app',
    measurementId: 'G-ESEK74XGHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQHhD6odsThX-AhSQor0XBuTldQgg_WnI',
    appId: '1:889075244343:android:b11882d306252cbe57ceb2',
    messagingSenderId: '889075244343',
    projectId: 'presence-app-26d2d',
    storageBucket: 'presence-app-26d2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnzQi8Og-JKvL5Italyw68y6JDCti1Eqk',
    appId: '1:889075244343:ios:d37e28afe12b3d0c57ceb2',
    messagingSenderId: '889075244343',
    projectId: 'presence-app-26d2d',
    storageBucket: 'presence-app-26d2d.firebasestorage.app',
    iosBundleId: 'com.example.presenceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnzQi8Og-JKvL5Italyw68y6JDCti1Eqk',
    appId: '1:889075244343:ios:d37e28afe12b3d0c57ceb2',
    messagingSenderId: '889075244343',
    projectId: 'presence-app-26d2d',
    storageBucket: 'presence-app-26d2d.firebasestorage.app',
    iosBundleId: 'com.example.presenceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNf8uQ6LbE1D-lz8bq8ccGP1JsjB6_4fU',
    appId: '1:889075244343:web:da82054550c7c01257ceb2',
    messagingSenderId: '889075244343',
    projectId: 'presence-app-26d2d',
    authDomain: 'presence-app-26d2d.firebaseapp.com',
    storageBucket: 'presence-app-26d2d.firebasestorage.app',
    measurementId: 'G-J79J6FTMCH',
  );
}
